name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # ou "main", dependendo da configuração do seu repositório

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # ajuste a versão conforme necessário

      - name: Instalar dependências
        run: npm install

      - name: Construir o projeto
        run: npm run build  # ajuste se necessário

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend  # ajuste para o diretório correto do seu site
